//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kurs_rab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts
    {
        public string Login { get; set; }
        public string Pass { get; set; }
        public string Status { get; set; }
        public string Role { get; set; }
    }
}
