//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kurs_rab
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class krEntities : DbContext
    {
        public krEntities()
            : base("name=krEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accounts> Accounts { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Заказы> Заказы { get; set; }
        public virtual DbSet<Покупатель> Покупатель { get; set; }
        public virtual DbSet<Покупки> Покупки { get; set; }
        public virtual DbSet<ПокупкиТоваров> ПокупкиТоваров { get; set; }
        public virtual DbSet<Поставщики> Поставщики { get; set; }
        public virtual DbSet<Работники> Работники { get; set; }
        public virtual DbSet<Товары> Товары { get; set; }
        public virtual DbSet<ТоварыЗаказов> ТоварыЗаказов { get; set; }
        public virtual DbSet<Удаленные_товары> Удаленные_товары { get; set; }
    }
}
