//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kurs_rab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказы()
        {
            this.ТоварыЗаказов = new HashSet<ТоварыЗаказов>();
        }
    
        public int id_заказа { get; set; }
        public int id_работника { get; set; }
        public int id_поставщика { get; set; }
        public string Статус { get; set; }
        public Nullable<decimal> Цена { get; set; }
        public string Описание { get; set; }
    
        public virtual Поставщики Поставщики { get; set; }
        public virtual Работники Работники { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ТоварыЗаказов> ТоварыЗаказов { get; set; }
    }
}
