//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kurs_rab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Покупки
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Покупки()
        {
            this.ПокупкиТоваров = new HashSet<ПокупкиТоваров>();
        }
    
        public int id_покупки { get; set; }
        public int id_покупателя { get; set; }
        public int id_работника { get; set; }
        public Nullable<decimal> Цена { get; set; }
    
        public virtual Покупатель Покупатель { get; set; }
        public virtual Работники Работники { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПокупкиТоваров> ПокупкиТоваров { get; set; }
    }
}
