//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kurs_rab
{
    using System;
    using System.Collections.Generic;
    
    public partial class ТоварыЗаказов
    {
        public int id { get; set; }
        public int id_заказа { get; set; }
        public int id_товара { get; set; }
        public Nullable<int> Количество { get; set; }
    
        public virtual Заказы Заказы { get; set; }
        public virtual Товары Товары { get; set; }
    }
}
